### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by azwaans** [matsengrp/gapml#178]
Hello,
After installing all required packages and double checking with past issues (seidels’s issue from January 31), I am getting the following errors/failures when running python3 -m unittest. I seem to be able to use the package, but is that something that I should worry about? 

(After adding in PaddedBoundedPoisson and ZeroInflatedBoundedPoisson from a previous commit I am left with only the failure) 

======================================================================
ERROR: tests.test_bounded_poisson (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_bounded_poisson
Traceback (most recent call last):
  File "/Users/antoinezwaans/opt/miniconda3/envs/snakes/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/antoinezwaans/opt/miniconda3/envs/snakes/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/antoinezwaans/gapml/gestalt/tests/test_bounded_poisson.py", line 4, in <module>
    from bounded_distributions import PaddedBoundedPoisson, ZeroInflatedBoundedPoisson
ImportError: cannot import name 'PaddedBoundedPoisson'

======================================================================
ERROR: tests.test_clt_likelihood_trim (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_clt_likelihood_trim
Traceback (most recent call last):
  File "/Users/antoinezwaans/opt/miniconda3/envs/snakes/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/antoinezwaans/opt/miniconda3/envs/snakes/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/antoinezwaans/gapml/gestalt/tests/test_clt_likelihood_trim.py", line 10, in <module>
    from bounded_distributions import ZeroInflatedBoundedPoisson, PaddedBoundedPoisson
ImportError: cannot import name 'ZeroInflatedBoundedPoisson'

======================================================================
FAIL: test_multifurc_vs_bifurc (tests.test_clt_likelihood_calc.LikelihoodCalculationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/antoinezwaans/gapml/gestalt/tests/test_clt_likelihood_calc.py", line 363, in test_multifurc_vs_bifurc
    self.assertTrue(np.isclose(multifurc_log_lik, bifurc_log_lik))
AssertionError: array([False]) is not true

----------------------------------------------------------------------
Ran 51 tests in 195.772s

FAILED (failures=1, errors=2)

////// After adding in code from previous commit

======================================================================
FAIL: test_multifurc_vs_bifurc (tests.test_clt_likelihood_calc.LikelihoodCalculationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/Users/antoinezwaans/gapml/gestalt/tests/test_clt_likelihood_calc.py", line 363, in test_multifurc_vs_bifurc
  self.assertTrue(np.isclose(multifurc_log_lik, bifurc_log_lik))
AssertionError: array([False]) is not true

----------------------------------------------------------------------
Ran 51 tests in 221.654s

FAILED (failures=1)

**Comment by jjfeng** [comment]
Hi, thanks for pointing this out. It's not a big deal -- I think the thresholds for `np.isclose` are a bit too stringent. I just ran the test and got  -46.56065392 vs -46.55951641. I'm going to relax the threshold used in the test to prevent future confusions.
